name: Update README with Codewars Stats

on:
    schedule:
        - cron: '0 20 * * *'
    push:
        branches:
            - main

jobs:
    update-readme:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Fetch Codewars Data
              id: fetch_codewars
              run: |
                  API_RESPONSE=$(curl -s https://www.codewars.com/api/v1/users/muenzi01)
                  echo "$API_RESPONSE" > codewars.json
                  echo "API Response:"
                  cat codewars.json

            - name: Extract Data from Codewars
              id: extract_data
              run: |
                  if [ ! -f codewars.json ]; then
                    echo "Error: codewars.json file not found"
                    exit 1
                  fi

                  USERNAME=$(jq -r '.username // empty' codewars.json)
                  HONOR=$(jq -r '.honor // empty' codewars.json)
                  OVERALL_RANK=$(jq -r '.ranks.overall.name // empty' codewars.json)
                  OVERALL_SCORE=$(jq -r '.ranks.overall.score // empty' codewars.json)

                  if [ -z "$USERNAME" ] || [ -z "$HONOR" ] || [ -z "$OVERALL_RANK" ] || [ -z "$OVERALL_SCORE" ]; then
                    echo "Error: Failed to extract data from codewars.json"
                    echo "Content of codewars.json:"
                    cat codewars.json
                    exit 1
                  fi

                    sed -i 's/\(<!-- CODEWARS_USERNAME -->\).*\(<!-- CODEWARS_USERNAME -->\)/\1 '"$USERNAME"' \2/' README.md
                    sed -i 's/\(<!-- CODEWARS_HONOR -->\).*\(<!-- CODEWARS_HONOR -->\)/\1 '"$HONOR"' \2/' README.md
                    sed -i 's/\(<!-- CODEWARS_OVERALL_RANK -->\).*\(<!-- CODEWARS_OVERALL_RANK -->\)/\1 '"$OVERALL_RANK"' \2/' README.md
                    sed -i 's/\(<!-- CODEWARS_OVERALL_SCORE -->\).*\(<!-- CODEWARS_OVERALL_SCORE -->\)/\1 '"$OVERALL_SCORE"' \2/' README.md

            - name: Commit and Push Changes
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add README.md
                  git diff --quiet && git diff --staged --quiet || (git commit -m "Update README with Codewars stats" && git push)

            - name: Debug Output
              run: |
                  echo "Content of README.md:"
                  cat README.md
                  echo "New Username: $USERNAME"
                  echo "New Honor: $HONOR"
                  echo "New Overall Rank: $OVERALL_RANK"
                  echo "New Overall Score: $OVERALL_SCORE"
