name: Update README with Codewars Stats

on:
    schedule:
        - cron: '0 * * * *'
    push:
        branches:
            - main

jobs:
    update-readme:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Fetch Codewars Data
              id: fetch_codewars
              run: |
                  API_RESPONSE=$(curl -s https://www.codewars.com/api/v1/users/muenzi01)
                  echo "$API_RESPONSE" > codewars.json
                  echo "API Response:"
                  cat codewars.json

            - name: Extract Data from Codewars
              id: extract_data
              run: |
                  if [ ! -f codewars.json ]; then
                    echo "Error: codewars.json file not found"
                    exit 1
                  fi

                  CW_USERNAME=$(jq -r '.username // empty' codewars.json)
                  CW_HONOR=$(jq -r '.honor // empty' codewars.json)
                  CW_RANK=$(jq -r '.ranks.overall.name // empty' codewars.json)
                  CW_SCORE=$(jq -r '.ranks.overall.score // empty' codewars.json)
                  LANG_RANKS=$(jq -r '.ranks.languages | to_entries[] | "* \(.key): \(.value.name) (Score: \(.value.score))"' codewars.json)

                  echo "CW_USERNAME=$CW_USERNAME" >> $GITHUB_ENV
                  echo "CW_HONOR=$CW_HONOR" >> $GITHUB_ENV
                  echo "CW_RANK=$CW_RANK" >> $GITHUB_ENV
                  echo "CW_SCORE=$CW_SCORE" >> $GITHUB_ENV
                  echo "$LANG_RANKS" >> lang_ranks.txt

                  if [ -z "$CW_USERNAME" ] || [ -z "$CW_HONOR" ] || [ -z "$CW_RANK" ] || [ -z "$CW_SCORE" ]; then
                    echo "Error: Failed to extract data from codewars.json"
                    echo "Content of codewars.json:"
                    cat codewars.json
                    echo "Extracted values:"
                    echo "Username: $CW_USERNAME"
                    echo "Honor: $CW_HONOR"
                    echo "Rank: $CW_RANK"
                    echo "Score: $CW_SCORE"
                    exit 1
                  fi

            - name: Update README
              run: |
                  sed -i 's/\*\*Username\*\*: [a-zA-Z0-9]* <!-- CODEWARS_USERNAME -->/\*\*Username\*\*: '"$CW_USERNAME"' <!-- CODEWARS_USERNAME -->/' README.md
                  sed -i 's/\*\*Honor\*\*: [0-9]* <!-- CODEWARS_HONOR -->/\*\*Honor\*\*: '"$CW_HONOR"' <!-- CODEWARS_HONOR -->/' README.md
                  sed -i 's/\*\*Overall Rank\*\*:.*<!-- CODEWARS_OVERALL_RANK -->/\*\*Rank\*\*: '"$CW_RANK"' <!-- CODEWARS_OVERALL_RANK -->/' README.md
                  sed -i 's/\*\*Overall Score\*\*:.*<!-- CODEWARS_OVERALL_SCORE -->/\*\*Score\*\*: '"$CW_SCORE"' <!-- CODEWARS_OVERALL_SCORE -->/' README.md

                  if grep -q "<!-- CODEWARS_LANGUAGE_RANKS -->" README.md; then
                      sed -i '/<!-- CODEWARS_LANGUAGE_RANKS -->/{n;d}' README.md
                      echo -e "\n### Language Ranks:\n<!-- CODEWARS_LANGUAGE_RANKS -->" >> README.md
                      while IFS= read -r line; do
                          echo "* $line" >> README.md
                      done < lang_ranks.txt
                  else
                      echo -e "\n### Language Ranks:\n<!-- CODEWARS_LANGUAGE_RANKS -->" >> README.md
                      while IFS= read -r line; do
                          echo "* $line" >> README.md
                      done < lang_ranks.txt
                  fi

            - name: Commit and Push Changes
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add README.md
                  git diff --quiet && git diff --staged --quiet || (git commit -m "Update README with Codewars stats" && git push)

            - name: Debug Output
              run: |
                  echo "Content of README.md:"
                  cat README.md
                  echo "New Username: ${{ env.CW_USERNAME }}"
                  echo "New Honor: ${{ env.CW_HONOR }}"
                  echo "New Overall Rank: ${{ env.CW_RANK }}"
                  echo "New Overall Score: ${{ env.CW_SCORE }}"
                  echo "New Language Ranks:"
                  cat lang_ranks.txt
