name: Update README with Codewars Stats

on:
    schedule:
        - cron: '0 20 * * *'
    push:
        branches:
            - main

jobs:
    update-readme:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Fetch Codewars Data
              id: fetch_codewars
              run: |
                  API_RESPONSE=$(curl -s https://www.codewars.com/api/v1/users/muenzi01)
                  echo "$API_RESPONSE" > codewars.json

            - name: Extract Data from Codewars
              id: extract_data
              run: |
                  USERNAME=$(jq -r '.username' codewars.json)
                  HONOR=$(jq -r '.honor' codewars.json)
                  OVERALL_RANK=$(jq -r '.ranks.overall.name' codewars.json)
                  OVERALL_SCORE=$(jq -r '.ranks.overall.score' codewars.json)

                  sed -i 's/\(<!-- CODEWARS_USERNAME -->\).*\(<!-- CODEWARS_USERNAME -->\)/\1 '"$USERNAME"' \2/' README.md
                  sed -i 's/\(<!-- CODEWARS_HONOR -->\).*\(<!-- CODEWARS_HONOR -->\)/\1 '"$HONOR"' \2/' README.md
                  sed -i 's/\(<!-- CODEWARS_OVERALL_RANK -->\).*\(<!-- CODEWARS_OVERALL_RANK -->\)/\1 '"$OVERALL_RANK"' \2/' README.md
                  sed -i 's/\(<!-- CODEWARS_OVERALL_SCORE -->\).*\(<!-- CODEWARS_OVERALL_SCORE -->\)/\1 '"$OVERALL_SCORE"' \2/' README.md

            - name: Commit and Push Changes
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add README.md
                  git diff --quiet && git diff --staged --quiet || (git commit -m "Update README with Codewars stats" && git push)
