name: Update README with Codewars Stats

on:
    schedule:
        - cron: '0 * * * *'
    push:
        branches:
            - main

jobs:
    update-readme:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Fetch Codewars Data
              id: fetch_codewars
              run: |
                  API_RESPONSE=$(curl -s https://www.codewars.com/api/v1/users/muenzi01)
                  echo "$API_RESPONSE" > codewars.json
                  echo "API Response:"
                  cat codewars.json

            - name: Clear old language ranks
              run: echo "" > lang_ranks.md

            - name: Extract Data from Codewars
              id: extract_data
              run: |
                  if [ ! -f codewars.json ]; then
                    echo "Error: codewars.json file not found"
                    exit 1
                  fi

                  CW_LEADERBOARD=$(jq -r '.leaderboardPosition // empty' codewars.json)
                  CW_HONOR=$(jq -r '.honor // empty' codewars.json)
                  CW_COMPLETED=$(jq -r '.codeChallenges.totalCompleted // empty' codewars.json)
                  CW_SCORE=$(jq -r '.ranks.overall.score // empty' codewars.json)
                  LANG_RANKS=$(jq -r '.ranks.languages | to_entries[] | "* **\(.key | ascii_upcase_first | gsub("script"; "Script"))**: \(.value.name | ascii_upcase_first) (Score: \(.value.score))"' codewars.json)

                  echo "CW_LEADERBOARD=$CW_LEADERBOARD" >> $GITHUB_ENV
                  echo "CW_HONOR=$CW_HONOR" >> $GITHUB_ENV
                  echo "CW_COMPLETED=$CW_COMPLETED" >> $GITHUB_ENV
                  echo "CW_SCORE=$CW_SCORE" >> $GITHUB_ENV
                  echo "$LANG_RANKS" >> lang_ranks.md

                  if [ -z "$CW_LEADERBOARD" ] || [ -z "$CW_HONOR" ] || [ -z "$CW_COMPLETED" ] || [ -z "$CW_SCORE" ]; then
                    echo "Error: Failed to extract data from codewars.json"
                    echo "Content of codewars.json:"
                    cat codewars.json
                    echo "Extracted values:"
                    echo "Username: $CW_LEADERBOARD"
                    echo "Honor: $CW_HONOR"
                    echo "Rank: $CW_COMPLETED"
                    echo "Score: $CW_SCORE"
                    exit 1
                  fi

            - name: Update README
              run: |
                  sed -i 's/\*\*Leaderboard Position\*\*: #[0-9]* <!-- CODEWARS_LEADERBOARD -->/\*\*Leaderboard Position\*\*: #'"$CW_LEADERBOARD"' <!-- CODEWARS_LEADERBOARD -->/' README.md
                  sed -i 's/\*\*Honor\*\*: [0-9]* <!-- CODEWARS_HONOR -->/\*\*Honor\*\*: '"$CW_HONOR"' <!-- CODEWARS_HONOR -->/' README.md
                  sed -i 's/\*\*Challenges Completed\*\*: [0-9]* <!-- CODEWARS_COMPLETED -->/\*\*Challenges Completed\*\*: '"$CW_COMPLETED"' <!-- CODEWARS_COMPLETED -->/' README.md
                  sed -i 's/\*\*Overall Score\*\*:.*<!-- CODEWARS_OVERALL_SCORE -->/\*\*Overall Score\*\*: '"$CW_SCORE"' <!-- CODEWARS_OVERALL_SCORE -->/' README.md

                  sed -i '/<!-- CODEWARS_LANGUAGE_RANKS -->/,$d' README.md

                  echo '<!-- CODEWARS_LANGUAGE_RANKS -->' >> README.md
                  cat lang_ranks.md >> README.md

            - name: Commit and Push Changes
              run: |
                  git pull
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add README.md
                  git diff --quiet && git diff --staged --quiet || (git commit -m "Update README with Codewars stats" && git push)

            - name: Debug Output
              run: |
                  echo "Content of README.md:"
                  cat README.md
                  echo "New Leaderboard Position: ${{ env.CW_LEADERBOARD }}"
                  echo "New Honor: ${{ env.CW_HONOR }}"
                  echo "New Challenges Completed: ${{ env.CW_COMPLETED }}"
                  echo "New Overall Score: ${{ env.CW_SCORE }}"
