name: Update README with Codewars Stats

on:
    schedule:
        - cron: '0 20 * * *'
    push:
        branches:
            - main

jobs:
    update-readme:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Fetch Codewars Data
              id: fetch_codewars
              run: |
                  API_RESPONSE=$(curl -s https://www.codewars.com/api/v1/users/muenzi01)
                  echo "$API_RESPONSE" > codewars.json

            - name: Extract Data from Codewars
              id: extract_data
              run: |
                  USERNAME=$(jq -r '.username' codewars.json)
                  HONOR=$(jq -r '.honor' codewars.json)
                  OVERALL_RANK=$(jq -r '.ranks.overall.name' codewars.json)
                  OVERALL_SCORE=$(jq -r '.ranks.overall.score' codewars.json)

                  sed -i "s/<!-- CODEWARS_USERNAME -->/${USERNAME} <!-- CODEWARS_USERNAME -->/g" README.md
                  sed -i "s/<!-- CODEWARS_HONOR -->/${HONOR} <!-- CODEWARS_HONOR -->/g" README.md
                  sed -i "s/<!-- CODEWARS_OVERALL_RANK -->/${OVERALL_RANK} <!-- CODEWARS_OVERALL_RANK -->/g" README.md
                  sed -i "s/<!-- CODEWARS_OVERALL_SCORE -->/${OVERALL_SCORE} <!-- CODEWARS_OVERALL_SCORE -->/g" README.md

            - name: Commit and Push Changes
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add .
                  git commit -m "Update README with Codewars stats"
                  git push
