name: Update README with Codewars Stats

on:
    schedule:
        - cron: '0 * * * *'
    push:
        branches:
            - main

jobs:
    update-readme:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Fetch Codewars Data
              id: fetch_codewars
              run: |
                  API_RESPONSE=$(curl -s https://www.codewars.com/api/v1/users/muenzi01)
                  echo "$API_RESPONSE" > codewars.json
                  echo "API Response:"
                  cat codewars.json

            - name: Clear old language ranks
              run: echo "" > lang_ranks.md

            - name: Extract Data from Codewars
              id: extract_data
              run: |
                  if [ ! -f codewars.json ]; then
                    echo "Error: codewars.json file not found"
                    exit 1
                  fi

                  CW_LEADERBOARD=$(jq -r '.leaderboardPosition // empty' codewars.json)
                  CW_COMPLETED=$(jq -r '.codeChallenges.totalCompleted // empty' codewars.json)
                  CW_SCORE=$(jq -r '.ranks.overall.score // empty' codewars.json)
                  LANG_RANKS=$(jq -r '.ranks.languages | to_entries[] | select(.value.score > 40) | "\(.key): \(.value.rank) (Score: \(.value.score))"' codewars.json)

                  TRANSFORMED_LANG_RANKS=""
                  while IFS= read -r line; do
                      key=$(echo "$line" | cut -d':' -f1 | sed -e 's/^\(.\)/\U\1/' -e 's/script/Script/')
                      value=$(echo "$line" | cut -d':' -f2-)
                      rank=$(echo "$value" | sed -E 's/\(Score: [0-9]+\)//' | xargs)
                      score=$(echo "$value" | grep -oP '(?<=Score: )\d+')
                      TRANSFORMED_LANG_RANKS="$TRANSFORMED_LANG_RANKS* **$key**: Rank: $rank - Score: $score"$'\n'
                  done <<< "$LANG_RANKS"

                  echo "CW_LEADERBOARD=$CW_LEADERBOARD" >> $GITHUB_ENV
                  echo "CW_COMPLETED=$CW_COMPLETED" >> $GITHUB_ENV
                  echo "CW_SCORE=$CW_SCORE" >> $GITHUB_ENV
                  echo "$TRANSFORMED_LANG_RANKS" >> lang_ranks.md

                  if [ -z "$CW_LEADERBOARD" ] || [ -z "$CW_COMPLETED" ] || [ -z "$CW_SCORE" ]; then
                    echo "Error: Failed to extract data from codewars.json"
                    echo "Content of codewars.json:"
                    cat codewars.json
                    echo "Extracted values:"
                    echo "Leaderboard Position: $CW_LEADERBOARD"
                    echo "Challenges Completed: $CW_COMPLETED"
                    echo "Overall Score: $CW_SCORE"
                    exit 1
                  fi

            - name: Update README
              run: |
                  sed -i 's/\*\*Leaderboard Position\*\*: #[0-9]* <!-- CODEWARS_LEADERBOARD -->/\*\*Leaderboard Position\*\*: #'"$CW_LEADERBOARD"' <!-- CODEWARS_LEADERBOARD -->/' README.md
                  sed -i 's/\*\*Challenges Completed\*\*: [0-9]* <!-- CODEWARS_COMPLETED -->/\*\*Challenges Completed\*\*: '"$CW_COMPLETED"' <!-- CODEWARS_COMPLETED -->/' README.md
                  sed -i 's/\*\*Overall Score\*\*:.*<!-- CODEWARS_OVERALL_SCORE -->/\*\*Overall Score\*\*: '"$CW_SCORE"' <!-- CODEWARS_OVERALL_SCORE -->/' README.md

                  sed -i '/<!-- CODEWARS_LANGUAGE_RANKS -->/,$d' README.md

                  echo '<!-- CODEWARS_LANGUAGE_RANKS -->' >> README.md
                  cat lang_ranks.md >> README.md

            - name: Commit and Push Changes
              run: |
                  git pull
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add README.md
                  git diff --quiet && git diff --staged --quiet || (git commit -m "Update README with Codewars stats" && git push)

            - name: Debug Output
              run: |
                  echo "Content of README.md:"
                  cat README.md
                  echo "New Leaderboard Position: ${{ env.CW_LEADERBOARD }}"
                  echo "New Challenges Completed: ${{ env.CW_COMPLETED }}"
                  echo "New Overall Score: ${{ env.CW_SCORE }}"
